version: '3.4'

services:
  catelogapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=catalog;Port=5432;Database=CatalogDb; User Id=postgres;password=postgres;Pooling=true;Include Error Detail=true
    ports:
      - "8080"
      - "8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

# version: '3.4'
 
# services:
#   catalogdb:
#     container_name: catalogdb
#     environment:
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=postgres
#       - POSTGRES_DB=CatalogDb
#     restart: always
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_catalog:/var/lob/postgresql/data/ 