version: '3.4'

services:
  catelogapi:
    image: ${DOCKER_REGISTRY-}catelogapi
    build:
      context: .
      dockerfile: Services/Catelog/CatelogAPI/Dockerfile
    ports:
    - 8080:80

# version: '3.4'
 
# services:
#     catalogdb:
#         image: postgres
#     catalog.api:
#       image: ${DOCKER_REGISTRY-}catalogapi
#       build:
#         context: .
#         dockerfile: Catalog.API/Dockerfile
 
# volumes:
#     postgres_catalog:
